export TYPST_FONT_PATHS := "fonts:typst-fonts"

zh_source := "cv.regular.typ"
zh_output := "cv.regular.pdf"
en_source := "cv-en.typ"
en_output := "cv-en.pdf"
gnu_source := "cv.gnu.typ"
gnu_output := "cv.gnu.pdf"

# Build all resumes.
default: build

# Build Chinese, English, and GNU-style PDFs.
build: build-zh build-en build-gnu

# Remove PDFs generated by this justfile.
clean:
    rm -f {{zh_output}} {{en_output}} {{gnu_output}}

# Build the Chinese PDF.
build-zh:
    typst compile {{zh_source}} {{zh_output}}

# Build the English PDF.
build-en:
    typst compile {{en_source}} {{en_output}}

# Build the GNU-style Chinese PDF.
build-gnu:
    typst compile {{gnu_source}} {{gnu_output}}

# Build and open the Chinese PDF once.
open-zh:
    typst compile {{zh_source}} {{zh_output}} --open

# Build and open the English PDF once.
open-en:
    typst compile {{en_source}} {{en_output}} --open

# Build and open the GNU-style Chinese PDF once.
open-gnu:
    typst compile {{gnu_source}} {{gnu_output}} --open

# Rebuild and preview the Chinese PDF on every change.
watch-zh:
    typst watch {{zh_source}} {{zh_output}} --open

# Rebuild and preview the English PDF on every change.
watch-en:
    typst watch {{en_source}} {{en_output}} --open

# Rebuild and preview the GNU-style Chinese PDF on every change.
watch-gnu:
    typst watch {{gnu_source}} {{gnu_output}} --open
