export TYPST_FONT_PATHS := "fonts:typst-fonts"

zh_source := "cv.regular.typ"
zh_output := "cv.regular.pdf"
en_source := "cv-en.typ"
en_output := "cv-en.pdf"

# Build both resumes.
default: build

# Build both Chinese and English PDFs.
build: build-zh build-en

# Remove PDFs generated by this justfile.
clean:
    rm -f {{zh_output}} {{en_output}}

# Build the Chinese PDF.
build-zh:
    typst compile {{zh_source}} {{zh_output}}

# Build the English PDF.
build-en:
    typst compile {{en_source}} {{en_output}}

# Build and open the Chinese PDF once.
open-zh:
    typst compile {{zh_source}} {{zh_output}} --open

# Build and open the English PDF once.
open-en:
    typst compile {{en_source}} {{en_output}} --open

# Rebuild and preview the Chinese PDF on every change.
watch-zh:
    typst watch {{zh_source}} {{zh_output}} --open

# Rebuild and preview the English PDF on every change.
watch-en:
    typst watch {{en_source}} {{en_output}} --open
